services:
    reservations:
        restart: always
        build:
            context: .
            dockerfile: ./apps/reservations/Dockerfile
            target: development
        command: sh -c "yarn install && yarn run start:dev:reservations"
        env_file:
            - ./apps/reservations/.env
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
    auth:
        restart: always
        build:
            context: .
            dockerfile: ./apps/auth/Dockerfile
            target: development
        command: sh -c "yarn install && yarn run start:dev:auth"
        env_file:
            - ./apps/auth/.env
        ports:
            - '3001:3001'
        volumes:
            - .:/usr/src/app
    mongo:
        image: mongo
        ports:
            - 127.0.0.1:27017:27017
        # This command will stop mongo from flooding the terminal with hard to read logs
        command: mongod --quiet --logpath /dev/null
